server:
  port: 8080
 # context-path: /jude
  

spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_jude
      username: root
      password: 123456
   jpa:
     # update 最常用的属性，第一次加载hibernate时根据model类会自动建立起表的结构（前提是先建立好数据库），以后加载
     #hibernate时根据 model类自动更新表结构，即使表结构改变了但表中的行仍然存在不会删除以前的行。要注意的是当部署到服务器
     #后，表结构是不会被马上建立起来的，是要等 应用第一次运行起来后才会。
     hibernate.ddl-auto: update
     show-sql: true         #是否打印出自动生产的SQL，方便调试的时候查看
   thymeleaf:
    cache: false           #是关闭thymeleaf的缓存，不然在开发过程中修改页面不会立刻生效需要重启，生产可配置为true。
